# Generated from `brew tap`, `brew leaves` and `brew list --cask` on G1459.
# Prune freely; once the list is trimmed, set cleanup = "zap" so anything not
# listed here gets uninstalled on switch.
{
  homebrew = {
    enable = true;

    onActivation = {
      autoUpdate = false;
      upgrade = false;
      cleanup = "none";
    };

    taps = [
      "azure/kubelogin"
      "dart-lang/dart"
      "guilospanck/tap"
      "hashicorp/tap"
      "heroku/brew"
      "int128/kubelogin"
      "mongodb/brew"
      "peonping/tap"
      "railwayapp/railway"
      "raine/consult-llm"
      "raine/workmux"
      "sass/sass"
      "shodan-public/shodan"
      "stripe/stripe-cli"
    ];

    brews = [
      "act"
      "asdf"
      "bash"
      "bat"
      "bison"
      "btop"
      "ccache"
      "cmake"
      "cocoapods"
      "colima"
      "coreutils"
      "curl"
      "dfu-util"
      "dive"
      "docker"
      "docker-buildx"
      "docker-compose"
      "eza"
      "fd"
      "ffmpeg"
      "ffmpeg-full"
      "flex"
      "fzf"
      "gh"
      "git"
      "gitleaks"
      "glow"
      "go"
      "golang-migrate"
      "gperf"
      "guilospanck/tap/modelgen"
      "helm"
      "hey"
      "htop"
      "hugo"
      "jpeg"
      "jq"
      "just"
      "kind"
      "kubectl"
      "lld"
      "mariadb"
      "maven"
      "minikube"
      "mise"
      "mkcert"
      "neovim"
      "nginx"
      "ninja"
      "nmap"
      "node"
      "nvm"
      "odin"
      "opencode"
      "openssl@1.1"
      "opentofu"
      "pipx"
      "pkgconf"
      "pngpaste"
      "pngquant"
      "poppler"
      "postgresql@14"
      "pre-commit"
      "python@3.12"
      "qemu"
      "raine/consult-llm/consult-llm"
      "raine/workmux/workmux"
      "redis"
      "shellcheck"
      "sops"
      "starship"
      "tectonic"
      "telnet"
      "tldr"
      "tmux"
      "tree"
      "trivy"
      "typos-cli"
      "watch"
      "wget"
      "xcodegen"
      "yarn"
      "yt-dlp"
      "z"
      "zig"
      "zlib"
      "zsh"
      "zsh-vi-mode"
    ];

    casks = [
      "guilospanck/tap/ai-usage-bar"
      "background-music"
      "clipy"
      "dbeaver-community"
      "fig"
      "gcloud-cli"
      "ghostty"
      "google-cloud-sdk"
      "karabiner-elements"
      "keycastr"
      "logitech-options"
      "ngrok"
      "notion"
      "obs"
      "postman"
      "secretive"
      "shodan-public/shodan/shodan-terminal"
    ];
  };
}
