[env]
TERM = "xterm-256color"

# [colors]
# transparent_background_colors = true

[window]
padding.x = 4
padding.y = 3
decorations = "None"
opacity = 1
option_as_alt = "Both"
dynamic_title = true
startup_mode = "Maximized"

[shell]
program = "/bin/zsh"
args = ["--login", "-c", "zellij"]

[keyboard]
bindings = [
  { key = "Plus",  mods = "Control", action="IncreaseFontSize" }, # Increases font size
  { key = "=",  mods = "Control", action="IncreaseFontSize" }, # Increases font size
  { key = "Minus",  mods = "Control", action="DecreaseFontSize" }, # Decreases font size

  { key = "e",  mods = "Command", chars = "\uE120" }, # Open new Zellij panel on the right
  { key = "n",  mods = "Command", chars = "\uE121" }, # Open new Zellij tab 
  { key = "w",  mods = "Command", chars = "\uE122" }, # Close Zellij tab 
  { key = "f",  mods = "Alt|Shift", chars = "\uE123" }, # Format code inside nvim (plugin: https://github.com/stevearc/conform.nvim
  { key = "b",  mods = "Command", chars = "\uE124" }, # Open explore inside nvim (default netrw using :Lex)
  { key = "p",  mods = "Command", chars = "\uE125" }, # Search for files in project in nvim (plugin: https://github.com/nvim-telescope/telescope.nvim)
  { key = "f",  mods = "Command", chars = "\uE127" }, # Search inside curremt file in nvim (telescope)
  { key = "f",  mods = "Control", chars = "\uE127" }, # Search inside curremt file in nvim (telescope)
  { key = "f",  mods = "Command|Shift", chars = "\uE128" }, # Search inside all files in the project directory in nvim (telescope)
  { key = ";",  mods = "Command", chars = "\uE129" }, # Comment current line of block in nvim (plugin:  https://github.com/numToStr/Comment.nvim))
  { key= "Key6", mods= "Command", chars= "\u001b[54;5u"}, # Ths is different from others because it is being mapped directly to Control 6 for vim https://github.com/alacritty/alacritty/issues/5680#issuecomment-2146475925, which is then being used to maximize window (plugin: default neovim)
  { key = "Tab",  mods = "Alt", chars = "\uE130" }, # Used to navigate to last opened file in nvim (plugin: default neovim)
  { key = "t",  mods = "Command", chars = "\uE132" }, # Used to find symbols in current file (telescope)
  { key = "t",  mods = "Control", chars = "\uE132" }, # Used to find symbols in current file (telescope) - Linux/MacOS binding
  { key = "l",  mods = "Command|Shift", chars = "\uE133" }, # Replace all occurrences of current under cursor word (using default vim commands)
  { key = "j",  mods = "Command", chars = "\uE134" }, # Move line to 1 below in visual mode (default vim commands)
  { key = "k",  mods = "Command", chars = "\uE135" }, # Move line to 1 to the top in visual mode (default vim commands)
  { key = "y",  mods = "Command", chars = "\uE136" }, # Switch between Zellij tabs
  { key = "g",  mods = "Command", chars = "\uE137" }, # Open new Zellij panel on the bottom
  { key = "p",  mods = "Command|Shift", chars = "\uE138" }, # Move up on Harpoon list inside nvim (plugin: https://github.com/ThePrimeagen/harpoon/tree/harpoon2)
  { key = "n",  mods = "Command|Shift", chars = "\uE139" }, # Move down on Harpoon list inside nvim (plugin: https://github.com/ThePrimeagen/harpoon/tree/harpoon2)
  { key = "m",  mods = "Command|Shift", chars = "\uE140" }, # Mark a file in Harpoon
  { key = "e",  mods = "Command|Shift", chars = "\uE141" }, # Open a Harpoon window
  { key = "a",  mods = "Command|Shift", chars = "\uE142" }, # Copy absolute path of current file
  { key = "x",  mods = "Command|Shift", chars = "\uE143" }, # Make current file executable
  { key = "Enter",  mods = "Command|Shift", action ="CreateNewWindow" } # Open a new Alacritty window
]
